module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Restified',
    'Roarind',
    'Cascading',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elik',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Crayon',
    'Pond',
    'Ground Camp',
    'Horse camp',
    'Ghost Towm',
    'Camp',
    'Dispersed Camp',
    'Blackcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliff',
    'Hollow'
]